services:
  scraping-webpi:
    image: genocs/scraping-webapi:1.0.0
    ports:
      - 5099:5400

    networks:
      - genocs
    # network_mode: host
    volumes:
      - scraping:/root

networks:
  genocs:
    name: genocs-network
    external: true

volumes:
  scraping:
    driver: local